name: bisabisnis
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_auth: ^4.16.0
  firebase_core: ^2.24.2
  google_fonts: ^6.1.0
  google_sign_in: ^6.2.1
  cloud_firestore: ^4.14.0
  carousel_slider: ^4.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/icons/businessman1.png
    - images/
